apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: equipment
  name: equipment
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
      nodePort: 30002
  selector:
    io.kompose.service: equipment
